# Generated by Django 5.2.14 on 2026-05-09 23:12

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario_id', models.BigAutoField(db_column='usuario_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=128, verbose_name='contrasena')),
                ('grupo', models.CharField(blank=True, choices=[('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('PREPA', 'PREPA'), ('LICENCIATURA', 'LICENCIATURA'), ('MAESTRIA', 'MAESTRIA'), ('DOCTORADO', 'DOCTORADO')], max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USUARIO', 'USUARIO')], default='USUARIO', max_length=10)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('is_staff', models.BooleanField(db_column='es_staff', default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
