# Generated by Django 5.2.14 on 2026-05-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquetipo',
            fields=[
                ('arquetipo_id', models.BigAutoField(db_column='arquetipo_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Arquetipo',
                'verbose_name_plural': 'Arquetipos',
                'db_table': 'arquetipo',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('examen_id', models.BigAutoField(db_column='examen_id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('VARK', 'VARK'), ('JUNG', 'JUNG')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='ExamenPresentado',
            fields=[
                ('examen_presentado_id', models.BigAutoField(db_column='examen_presentado_id', primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'EN_PROCESO'), ('FINALIZADO', 'FINALIZADO'), ('ANULADO', 'ANULADO')], default='EN_PROCESO', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes_presentados', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Examen presentado',
                'verbose_name_plural': 'Examenes presentados',
                'db_table': 'examen_presentado',
            },
        ),
        migrations.CreateModel(
            name='ExamenPresentadoRespuesta',
            fields=[
                ('examen_presentado_respuesta_id', models.BigAutoField(db_column='examen_presentado_respuesta_id', primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Examen presentado respuesta',
                'verbose_name_plural': 'Examenes presentados respuestas',
                'db_table': 'examen_presentado_respuesta',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.BigAutoField(db_column='pregunta_id', primary_key=True, serialize=False)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('respuesta_id', models.BigAutoField(db_column='respuesta_id', primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('valor', models.IntegerField(default=1)),
                ('codigo', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='JungResultado',
            fields=[
                ('examen_presentado', models.OneToOneField(db_column='examen_presentado_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resultado_jung', serialize=False, to='examenes.examenpresentado')),
                ('i_count', models.IntegerField(default=0)),
                ('e_count', models.IntegerField(default=0)),
                ('n_count', models.IntegerField(default=0)),
                ('s_count', models.IntegerField(default=0)),
                ('t_count', models.IntegerField(default=0)),
                ('f_count', models.IntegerField(default=0)),
                ('j_count', models.IntegerField(default=0)),
                ('p_count', models.IntegerField(default=0)),
                ('tipo_personalidad', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Jung resultado',
                'verbose_name_plural': 'Jung resultados',
                'db_table': 'jung_resultado',
            },
        ),
        migrations.CreateModel(
            name='VarkResultado',
            fields=[
                ('examen_presentado', models.OneToOneField(db_column='examen_presentado_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resultado_vark', serialize=False, to='examenes.examenpresentado')),
                ('v', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('k', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'VARK resultado',
                'verbose_name_plural': 'VARK resultados',
                'db_table': 'vark_resultado',
            },
        ),
    ]
