# Generated by Django 5.2.14 on 2026-05-09 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examenpresentado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_presentados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenpresentadorespuesta',
            name='examen_presentado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='examenes.examenpresentado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='examenes.examen'),
        ),
        migrations.AddField(
            model_name='examenpresentadorespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.pregunta'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='examenes.pregunta'),
        ),
        migrations.AddField(
            model_name='examenpresentadorespuesta',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.respuesta'),
        ),
        migrations.AddField(
            model_name='jungresultado',
            name='arquetipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examenes.arquetipo'),
        ),
        migrations.AddField(
            model_name='varkresultado',
            name='arquetipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examenes.arquetipo'),
        ),
        migrations.AddIndex(
            model_name='examenpresentado',
            index=models.Index(fields=['examen'], name='examen_pres_examen__f4bac4_idx'),
        ),
        migrations.AddIndex(
            model_name='examenpresentado',
            index=models.Index(fields=['usuario'], name='examen_pres_usuario_9f1989_idx'),
        ),
        migrations.AddIndex(
            model_name='examenpresentado',
            index=models.Index(fields=['grupo'], name='examen_pres_grupo_162ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='examenpresentado',
            index=models.Index(fields=['estado'], name='examen_pres_estado_5a1443_idx'),
        ),
        migrations.AddIndex(
            model_name='examenpresentado',
            index=models.Index(fields=['fecha_creacion'], name='examen_pres_fecha_c_2791cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='examenpresentadorespuesta',
            constraint=models.UniqueConstraint(fields=('examen_presentado', 'pregunta'), name='uq_examen_presentado_pregunta'),
        ),
    ]
